#!/bin/zsh

setup() {
  ZOTFILES="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
}

install_with_brew() {
  local to_install="${1}"
  brew install "$to_install"
}

install_with_brew_cask() {
  local to_install="${1}"
  brew cask install "$to_install"
}

install_git() {
  brew install git
  brew link git --force
}

install_git_duet() {
  brew install git-duet/tap/git-duet
}

install_golang() {
  brew install golang
}

install_iterm() {
  brew cask install iterm2
  ln -s "$ZOTFILES/com.googlecode.iterm2.plist" "$HOME/Library/Preferences/com.googlecode.iterm2.plist"
  defaults read "$HOME/Library/Preferences/com.googlecode.iterm2.plist"
}

install_omz() {
  git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
  chsh -s /bin/zsh
}

install_powerline() {
  echo "Installing powerline fonts\n"
  pushd "$HOME/workspace"
    git clone https://github.com/powerline/fonts.git powerline-fonts
    pushd powerline-fonts
      ./install.sh
    popd
  popd
}

link_dotfiles() {
  ln -s "$ZOTFILES/.zshrc" "$HOME/.zshrc"
  ln -s "$ZOTFILES/zagnoster.zsh-theme" "$HOME/.oh-my-zsh/themes/zagnoster.zsh-theme"
  cp "$ZOTFILES/.gitconfig" "$HOME/.gitconfig"

  #Link and read Spectacle prefs
  ln -s "$ZOTFILES/com.divisiblebyzero.Spectacle.plist" "$HOME/Library/Preferences/com.divisiblebyzero.Spectacle.plist"
  defaults read "$HOME/Library/Preferences/com.divisiblebyzero.Spectacle.plist"
}

install_neovim() {
  brew install neovim/neovim/neovim
  ln -s /usr/local/bin/nvim /usr/local/bin/vim
  source ~/.zshrc
  brew install python3
  pip3 install neovim
}

set_defaults() {
  defaults write NSGlobalDomain KeyRepeat 1
  defaults write NSGlobalDomain InitialKeyRepeat 15
}

main() {
  setup

  install_git
  install_git_duet
  install_golang
  install_with_brew "fzf"
  install_with_brew_cask "spectacle"
  install_with_brew_cask "google-chrome"
  install_iterm
  install_powerline
  install_neovim
  install_omz
  link_dotfiles
  set_defaults
}

main $@
